version: '3.8'

services:
  sentiment-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ai-sentiment-service
    ports:
      - "8000:8000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - DEBUG_MODE=false
      - LOG_LEVEL=INFO
      - MODEL_CACHE_DIR=/tmp/models
      - TRANSFORMERS_CACHE=/tmp/models
    volumes:
      # Mount models cache to persist downloaded models
      - model_cache:/app/models/cache
      # Mount logs for persistent logging (optional)
      - ./logs:/app/logs
      # Mount .env file if it exists
      - ../.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - sentiment-network

  # Optional: Add nginx reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: ai-sentiment-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - sentiment-api
  #   networks:
  #     - sentiment-network

volumes:
  model_cache:
    driver: local

networks:
  sentiment-network:
    driver: bridge